### ISSUE TITLE
make sure salt is per-question

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/nbgrader#10]
even in repeated test blocks!

**Comment by wiwang** [comment]
In each Jupyter cell, we parse the cell and create test case based on each code snippet, in function `async def _async_run_snippet(self, hash_snippet, snippet):`,  we generate the salt for each code snippet as below:
`        #create a random salt for this test
        salt = secrets.token_hex(8)
        if hash_snippet:
            self.log.debug('Salt: ' + salt)`

so we can confirm the salt is created per-question
